apiVersion: v1
kind: Service
metadata:
  name: gzabarte-frontend-svc
  labels: 
    tier: frontend
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
    - port: 5173
      nodePort: 30006
